# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

    The version of the OpenAPI document: v1
    Contact: support@clerk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clerk_backend_sdk.models.get_o_auth_access_token200_response_inner import GetOAuthAccessToken200ResponseInner

class TestGetOAuthAccessToken200ResponseInner(unittest.TestCase):
    """GetOAuthAccessToken200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOAuthAccessToken200ResponseInner:
        """Test GetOAuthAccessToken200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOAuthAccessToken200ResponseInner`
        """
        model = GetOAuthAccessToken200ResponseInner()
        if include_optional:
            return GetOAuthAccessToken200ResponseInner(
                object = '',
                external_account_id = '',
                provider_user_id = '',
                token = '',
                provider = '',
                public_metadata = None,
                label = '',
                scopes = [
                    ''
                    ],
                token_secret = ''
            )
        else:
            return GetOAuthAccessToken200ResponseInner(
        )
        """

    def testGetOAuthAccessToken200ResponseInner(self):
        """Test GetOAuthAccessToken200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
