# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

    The version of the OpenAPI document: v1
    Contact: support@clerk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clerk_backend_sdk.api.organization_invitations_api import OrganizationInvitationsApi


class TestOrganizationInvitationsApi(unittest.TestCase):
    """OrganizationInvitationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationInvitationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization_invitation(self) -> None:
        """Test case for create_organization_invitation

        Create and send an organization invitation
        """
        pass

    def test_create_organization_invitation_bulk(self) -> None:
        """Test case for create_organization_invitation_bulk

        Bulk create and send organization invitations
        """
        pass

    def test_get_organization_invitation(self) -> None:
        """Test case for get_organization_invitation

        Retrieve an organization invitation by ID
        """
        pass

    def test_list_organization_invitations(self) -> None:
        """Test case for list_organization_invitations

        Get a list of organization invitations
        """
        pass

    def test_list_pending_organization_invitations(self) -> None:
        """Test case for list_pending_organization_invitations

        Get a list of pending organization invitations
        """
        pass

    def test_revoke_organization_invitation(self) -> None:
        """Test case for revoke_organization_invitation

        Revoke a pending organization invitation
        """
        pass


if __name__ == '__main__':
    unittest.main()
