# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

    The version of the OpenAPI document: v1
    Contact: support@clerk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clerk_backend_sdk.api.o_auth_applications_api import OAuthApplicationsApi


class TestOAuthApplicationsApi(unittest.TestCase):
    """OAuthApplicationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthApplicationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_o_auth_application(self) -> None:
        """Test case for create_o_auth_application

        Create an OAuth application
        """
        pass

    def test_delete_o_auth_application(self) -> None:
        """Test case for delete_o_auth_application

        Delete an OAuth application
        """
        pass

    def test_get_o_auth_application(self) -> None:
        """Test case for get_o_auth_application

        Retrieve an OAuth application by ID
        """
        pass

    def test_list_o_auth_applications(self) -> None:
        """Test case for list_o_auth_applications

        Get a list of OAuth applications for an instance
        """
        pass

    def test_rotate_o_auth_application_secret(self) -> None:
        """Test case for rotate_o_auth_application_secret

        Rotate the client secret of the given OAuth application
        """
        pass

    def test_update_o_auth_application(self) -> None:
        """Test case for update_o_auth_application

        Update an OAuth application
        """
        pass


if __name__ == '__main__':
    unittest.main()
