# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

    The version of the OpenAPI document: v1
    Contact: support@clerk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clerk_backend_sdk.api.phone_numbers_api import PhoneNumbersApi


class TestPhoneNumbersApi(unittest.TestCase):
    """PhoneNumbersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PhoneNumbersApi()

    def tearDown(self) -> None:
        pass

    def test_create_phone_number(self) -> None:
        """Test case for create_phone_number

        Create a phone number
        """
        pass

    def test_delete_phone_number(self) -> None:
        """Test case for delete_phone_number

        Delete a phone number
        """
        pass

    def test_get_phone_number(self) -> None:
        """Test case for get_phone_number

        Retrieve a phone number
        """
        pass

    def test_update_phone_number(self) -> None:
        """Test case for update_phone_number

        Update a phone number
        """
        pass


if __name__ == '__main__':
    unittest.main()
