# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

    The version of the OpenAPI document: v1
    Contact: support@clerk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clerk_backend_sdk.api.beta_features_api import BetaFeaturesApi


class TestBetaFeaturesApi(unittest.TestCase):
    """BetaFeaturesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BetaFeaturesApi()

    def tearDown(self) -> None:
        pass

    def test_change_production_instance_domain(self) -> None:
        """Test case for change_production_instance_domain

        Update production instance domain
        """
        pass

    def test_update_instance_auth_config(self) -> None:
        """Test case for update_instance_auth_config

        Update instance settings
        """
        pass

    def test_update_production_instance_domain(self) -> None:
        """Test case for update_production_instance_domain

        Update production instance domain
        """
        pass


if __name__ == '__main__':
    unittest.main()
