# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

    The version of the OpenAPI document: v1
    Contact: support@clerk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clerk_backend_sdk.api.clients_api import ClientsApi


class TestClientsApi(unittest.TestCase):
    """ClientsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClientsApi()

    def tearDown(self) -> None:
        pass

    def test_get_client(self) -> None:
        """Test case for get_client

        Get a client
        """
        pass

    def test_get_client_list(self) -> None:
        """Test case for get_client_list

        List all clients
        """
        pass

    def test_verify_client(self) -> None:
        """Test case for verify_client

        Verify a client
        """
        pass


if __name__ == '__main__':
    unittest.main()
