# coding: utf-8

"""
    Clerk Backend API

    The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

    The version of the OpenAPI document: v1
    Contact: support@clerk.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clerk_backend_sdk.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_session_token_from_template(self) -> None:
        """Test case for create_session_token_from_template

        Create a session token from a jwt template
        """
        pass

    def test_get_session(self) -> None:
        """Test case for get_session

        Retrieve a session
        """
        pass

    def test_get_session_list(self) -> None:
        """Test case for get_session_list

        List all sessions
        """
        pass

    def test_revoke_session(self) -> None:
        """Test case for revoke_session

        Revoke a session
        """
        pass

    def test_verify_session(self) -> None:
        """Test case for verify_session

        Verify a session
        """
        pass


if __name__ == '__main__':
    unittest.main()
